//
//  CreateReservationModels.swift
//  PetGroomerShop
//
//  Created by Lee, Jeongsik on 2019/06/20.
//  Copyright (c) 2019 Lee, Jeongsik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateReservation
{
    struct ReservationFormFields
    {
        // MARK: Pet Info
        var petName: String
        var petSpecies: String
        
        // MARK: Pet Owner Info
        var ownerName: String
        var ownerPhone: String
        
        // MARK: Grooming Info
        var groomerName: String
        var groomTime: Date
        
        var id: String?
    }
    
    // MARK: Use cases
    
    enum CreateReservation
    {
        struct Request
        {
            var reservationFormFields: ReservationFormFields
        }
        struct Response
        {
            var reservation: Reservation?
        }
        struct ViewModel
        {
            var reservation: Reservation?
        }
    }
    
    enum EditReservation
    {
        struct Request
        {
        }
        struct Response
        {
            var reservation: Reservation
        }
        struct ViewModel
        {
            var reservationFormFields: ReservationFormFields
        }
    }
    
    enum UpdateReservation
    {
        struct Request
        {
            var reservationFormFields: ReservationFormFields
        }
        struct Response
        {
            var reservation: Reservation?
        }
        struct ViewModel
        {
            var reservation: Reservation?
        }
    }
}
