//
//  ShowReservationRouter.swift
//  PetGroomerShop
//
//  Created by Lee, Jeongsik on 2019/06/20.
//  Copyright (c) 2019 Lee, Jeongsik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowReservationRoutingLogic
{
    func routeToEditReservation(segue: UIStoryboardSegue?)
}

protocol ShowReservationDataPassing
{
    var dataStore: ShowReservationDataStore? { get }
}

class ShowReservationRouter: NSObject, ShowReservationRoutingLogic, ShowReservationDataPassing
{
    weak var viewController: ShowReservationViewController?
    var dataStore: ShowReservationDataStore?
    
    // MARK: Routing
    
    func routeToEditReservation(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! CreateReservationViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditReservation(source: dataStore!, destination: &destinationDS)
        } else {
            let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "CreateReservationVC") as! CreateReservationViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToEditReservation(source: dataStore!, destination: &destinationDS)
            navigateToEditReservation(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToEditReservation(source: ShowReservationViewController, destination: CreateReservationViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToEditReservation(source: ShowReservationDataStore, destination: inout CreateReservationDataStore)
    {
        destination.reservationToEdit = source.reservation
    }
}



