//
//  ShowReservationModels.swift
//  PetGroomerShop
//
//  Created by Lee, Jeongsik on 2019/06/20.
//  Copyright (c) 2019 Lee, Jeongsik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowReservation
{
    // MARK: Use cases
    
    enum GetReservation
    {
        struct Request
        {
        }
        struct Response
        {
            var reservation: Reservation
        }
        struct ViewModel
        {
            struct DisplayedReservation
            {
                var petName: String
                var groomTime: String
            }
            var displayedReservation: DisplayedReservation
        }
    }
}

