//
//  ShowReservationPresenter.swift
//  PetGroomerShop
//
//  Created by Lee, Jeongsik on 2019/06/20.
//  Copyright (c) 2019 Lee, Jeongsik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowReservationPresentationLogic
{
    func presentReservation(response: ShowReservation.GetReservation.Response)
}

class ShowReservationPresenter: ShowReservationPresentationLogic
{
    weak var viewController: ShowReservationDisplayLogic?
    
    let dateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .short
        dateFormatter.timeStyle = .none
        return dateFormatter
    }()
    
    // MARK: - Get reservation
    
    func presentReservation(response: ShowReservation.GetReservation.Response)
    {
        let reservation = response.reservation
        
        let date = dateFormatter.string(from: reservation.groomTime)
        let displayedReservation = ShowReservation.GetReservation.ViewModel.DisplayedReservation(petName: reservation.petName, groomTime: date)
        let viewModel = ShowReservation.GetReservation.ViewModel(displayedReservation: displayedReservation)
        viewController?.displayReservation(viewModel: viewModel)
    }
}

