//
//  ShowReservationInteractor.swift
//  PetGroomerShop
//
//  Created by Lee, Jeongsik on 2019/06/20.
//  Copyright (c) 2019 Lee, Jeongsik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowReservationBusinessLogic
{
    func getReservation(request: ShowReservation.GetReservation.Request)
}

protocol ShowReservationDataStore
{
    var reservation: Reservation! { get set }
}

class ShowReservationInteractor: ShowReservationBusinessLogic, ShowReservationDataStore
{
    var presenter: ShowReservationPresentationLogic?
    
    var reservation: Reservation!
    
    // MARK: - Get reservation
    
    func getReservation(request: ShowReservation.GetReservation.Request)
    {
        let response = ShowReservation.GetReservation.Response(reservation: reservation) // 여기야
        presenter?.presentReservation(response: response)
    }
}
