//
//  ListReservationsModels.swift
//  PetGroomerShop
//
//  Created by Lee, Jeongsik on 2019/06/21.
//  Copyright (c) 2019 Lee, Jeongsik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListReservations
{
    // MARK: Use cases
    
    enum FetchReservations
    {
        struct Request
        {
        }
        struct Response
        {
            var reservations: [Reservation]
        }
        struct ViewModel
        {
            struct DisplayedReservation
            {
                var petName: String
                var groomTime: String
            }
            var displayedReservations: [DisplayedReservation]
        }
    }
}
