//
//  ListReservationsInteractor.swift
//  PetGroomerShop
//
//  Created by Lee, Jeongsik on 2019/06/21.
//  Copyright (c) 2019 Lee, Jeongsik. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListReservationsBusinessLogic
{
    func fetchReservations(request: ListReservations.FetchReservations.Request)
}

protocol ListReservationsDataStore
{
    var reservations: [Reservation]? { get }
}

class ListReservationsInteractor: ListReservationsBusinessLogic, ListReservationsDataStore
{
    var presenter: ListReservationsPresentationLogic?
    
    var reservationsWorker = ReservationsWorker(reservationsStore: ReservationsMemStore())
    var reservations: [Reservation]?
    
    // MARK: - Fetch reservations
    
    func fetchReservations(request: ListReservations.FetchReservations.Request)
    {
        reservationsWorker.fetchReservations { (reservations) -> Void in
            self.reservations = reservations
            let response = ListReservations.FetchReservations.Response(reservations: reservations)
            self.presenter?.presentFetchedReservations(response: response)
        }
    }
}
